apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  labels:
    app: learning-platform
type: Opaque
stringData:
  POSTGRES_DB: learning_platform
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin123
