apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-pod
  labels:
    app: secret-demo
spec:
  containers:
    - name: secret-demo-container
      image: nginx:1.25
      ports:
        - containerPort: 80
      # envFrom:
      #   # # Each key in the ConfigMap becomes an environment variable
      #   # # No files are created
      #   # # Nothing is written to the filesystem
      #   - secretRef:
      #       name: db-secret

      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
