apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default # if not specified, the secret will be created in the default namespace
type: Opaque 
# this is the type of the secret, it can be 
# Opaque, kubernetes.io/dockerconfigjson, kubernetes.io/service-account-token, kubernetes.io/tls, bootstrap.kubernetes.io/token
# Opaque is the default type and it is used to store any kind of data
data:
# the data key is the name of the secret and the value is the value of the secret encoded in base64
  DB_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==
  DB_USER: YWRtaW5Vc2Vy