apiVersion: v1
kind: Pod
metadata:
  name: manual-pod
  labels:
    manual: pod
spec:
  nodeName: minikube-m02
  containers:
  - name: nginx
    image: nginx:1.25-alpine
    ports:
    - containerPort: 80


# same as the q1-pod.yaml but using nodeName instead of nodeSelector

# imperative way

# kubectl run manual-pod --image=nginx:1.25-alpine --port=80 --labels=manual=pod \
#   --overrides='{
#     "apiVersion": "v1",
#     "spec": {
#       "nodeName": "minikube-m02"
#     }
#   }'
