apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
  labels:
    app: configmap-demo
spec:
  containers:
    - name: configmap-demo-container
      image: nginx:1.25
      ports:
        - containerPort: 80

      # envFrom:
      # # Each key in the ConfigMap becomes an environment variable
      # # No files are created
      # # Nothing is written to the filesystem
      # - configMapRef:
      #     name: configmap-demo

      env:
        # Each key in the ConfigMap becomes an environment variable
        # a file is created in the container filesystem
        # the file is read only
        # the files path is /etc/config/
        # the file name is the key name
        # the file content is the key value
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap-demo
              key: APP_PORT
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: configmap-demo
              key: DATABASE_URL
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: configmap-demo
              key: LOG_LEVEL

      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
          readOnly: true

  volumes:
    - name: config-volume
      configMap:
        name: configmap-demo
